version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: rawsql-infrastructure-demo-db
    environment:
      POSTGRES_DB: infrastructure_demo
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_password
    ports:
      - "5433:5432" # Use different port to avoid conflicts
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U demo_user -d infrastructure_demo" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
